local builtin = require("dap")
vim.keymap.set("n", "<leader>db" , builtin.toggle_breakpoint , {}) 
vim.keymap.set("n", "<leader>dB" , builtin.clear_breakpoints , {})
vim.keymap.set("n", "<leader>dc" , builtin.continue , {})
vim.keymap.set("n", "<leader>di" , builtin.step_into , {})
vim.keymap.set("n", "<leader>do" , builtin.step_over , {})
vim.keymap.set("n", "<leader>dO" , builtin.step_out , {})
vim.keymap.set("n", "<leader>dq" , builtin.close , {})
vim.keymap.set("n", "<leader>dQ" , builtin.terminate , {})
vim.keymap.set("n", "<leader>dp" , builtin.pause , {})
vim.keymap.set("n", "<leader>dr" , builtin.restart_frame , {})
vim.keymap.set("n", "<leader>dR" , builtin.repl.toggle , {}) 
vim.keymap.set("n", "<leader>ds" , builtin.run_to_cursor , {})
