local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>fw", builtin.live_grep, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "gr", builtin.lsp_references, {})
vim.keymap.set("n", "gI", builtin.lsp_implementations, {})
vim.keymap.set("n", "gd", builtin.lsp_definitions, {})
vim.keymap.set("n", "<leader>lD", builtin.diagnostics, {})

vim.keymap.set("n", "<leader>f/", function()
	builtin.current_buffer_fuzzy_find()
end, {})

vim.keymap.set("n", "<leader>gt", function()
	builtin.git_status({ use_file_path = true })
end, {})
